mode: emo_in_gaze
device: cuda
dataset:
  dataset_dir: D:\datasets\xgaze_224
  raf_dataset_path: D:\datasets\RafDB
  fer_dataset_path: D:\datasets\fer2013_superresolution
  image_size: 224
  n_channels: 3
  mean: [ 0.485, 0.456, 0.406 ]  # RGB
  std: [ 0.229, 0.224, 0.225 ]  # RGB
  transform:
    train:
      horizontal_flip: True
      resize: 224
    val:
      resize: 224
    test:
      resize: 224

model:
  name: gaze_emotion
  backbone:
    name: tf_efficientnet_b0_ns # resnet18, tf_efficientnet_b2

train:
  val_first: False
  emo_pretrained: True
  gaze_pretrained: False
  resume_path: False
  wandb: True
  batch_size: 32
  optimizer: sgd
  base_lr: 0.001
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001
  no_weight_decay_on_bn: False
  class_weights: [1.2, 2, 2, 0.5, 0.8, 1, 1]
  label_smoothing: 0.2
  loss: SmoothL1
  seed: 0
  output_dir: D:\emotion_in_gaze\experiments\effnet\exp22_efficinetb0_classweights
  log_period: 100
  checkpoint_period: 1
  val_indices: [0, 1, 2]
  train_dataloader:
    num_workers: 2
    drop_last: False
    pin_memory: False
  val_dataloader:
    num_workers: 2
    pin_memory: False
  task_weights:
    gaze: 0.3
    emotion: 0.7

scheduler:
  epochs: 25
  type: cosine
  milestones: [8, 15]
  lr_decay: 0.1
  lr_min_factor: 0.00001

cudnn:
  benchmark: True
  deterministic: True