mode: MPIIFaceGaze
device: cuda
dataset:
  dataset_dir: datasets/MPIIFaceGaze.h5
transform:
  mpiifacegaze_face_size: 224
  mpiifacegaze_gray: False
model:
  name: resnet_simple
  backbone:
    name: resnet_simple
    pretrained: resnet18
    resnet_block: basic
    resnet_layers: [2, 2, 2]
test:
  test_id: 1
  checkpoint: experiments/mpiifacegaze/resnet_simple_14/exp01/01/checkpoint_0015.pth # /home/demon/.ptgaze/models/mpiifacegaze_resnet_simple.pth
  output_dir: experiments/mpiifacegaze/resnet_simple_14/exp01/01/eval
  batch_size: 256
  dataloader:
    num_workers: 4
    pin_memory: False
cudnn:
  benchmark: True
  deterministic: False
